### ISSUE TITLE
Not respecting previous windows position and size

### ISSUE THREAD

**Issue by evertonstz** [jgierer12/pocket-casts-linux#3] opened 2019-03-15 04:46 UTC
Hey, I'm on GNOME 3.30.2, on Manjaro, the app won't previous windows after closed, doesn't matter the sizer or position on the screen it was, if you close the app window and open it again the app will be opened maximized.

**Comment by jgierer12** [comment] 2019-03-15 12:28
Could you try the AppImage linked in #4 (if you previously installed with pacman, click "No" when asked about system integration)?

Persisting the window state was something I planned to do but never really got around to, but it was really easy to implement and works flawlessly on my machine (also GNOME 3.30.2 on Manjaro :raised_hands: ).

What's a bit weird is that on your machine, the window opens maximized, which it shouldn't based on the default options. Should this still happen with the PR's AppImage, please send me a screenshot of your GNOME Settings > `Devices` > `Displays`, as well as GNOME Tweaks > `Windows` to help me investigate further.

**Comment by evertonstz** [comment] 2019-03-15 17:20
Here's the behavior of this build on my system (nice to see firefox send getting used, it's a good service):

- first launch: opens maximixed like the pacman version, opening speed is normal. I changed the size, moved it around and closed the app;

- second launch: the window state persists and the splash screen will launch right with the size and position I left in the first run, but it'll take like 60 seconds for the app to fully load and go past the splash screen;

Strangely enough, I went and tried the pacman version I had installed in my system, and it's also not loading fast, since I did build it from AUR, I went and checked If I had uninstalled any dependecy, and they're all there. I can ping "play.pocketcasts.com" fine, so it seems to be related to my system. Strangely enough I didn't pushed any update since 2 days ago, and the appimage shouldn't care. I'm investigating, I've got this [error msg](https://i.imgur.com/mYvPtkw.png)...
The issue with the screen is solved in the appimage, tho.

**Comment by jgierer12** [comment] 2019-03-16 10:33
Huh, that error is exactly what I thought I had fixed with this:

https://github.com/jgierer12/pocket-casts-linux/blob/61ad837a9ebc06c450da9dbe5a1780ab8e11a390/src/index.js#L25

I'll need to investigate why it's still occurring.

**Comment by evertonstz** [comment] 2019-03-16 13:20
> Huh, that error is exactly what I thought I had fixed with this:
> 
> [pocket-casts-linux/src/index.js](https://github.com/jgierer12/pocket-casts-linux/blob/61ad837a9ebc06c450da9dbe5a1780ab8e11a390/src/index.js#L25)
> 
> Line 25 in [61ad837](/jgierer12/pocket-casts-linux/commit/61ad837a9ebc06c450da9dbe5a1780ab8e11a390)
>  const windowStateObj = JSON.parse(JSON.stringify(windowState)); 
> 
> I'll need to investigate why it's still occurring.

If you wish I can open another issue so you can close this one as apparently you fixed it. This error seems to be erratic, as it did not happened today, I'm using the app fine here. Strange.

**Comment by jgierer12** [comment] 2019-03-20 11:48
No, I am pretty sure that is a regression issue directly caused by #4, so I will only merge that once this issue is fixed, and continue discussion about this bug in #4 too.

**Comment by evertonstz** [comment] 2019-03-20 15:09
> No, I am pretty sure that is a regression issue directly caused by #4, so I will only merge that once this issue is fixed, and continue discussion about this bug in #4 too.

Ok, I'm always available if you need any testing.

**Closed as completed** 2019-03-21 14:18 UTC
Labels: enhancement
